### ISSUE TITLE
[UNRELATED] Hey..

### ISSUE THREAD

**Issue by ghost** [Explosion-Scratch/explosion-scratch.github.io#12]
So i made a forum about coding, and i also saw that you like helping around on the scratch forums!
So i was wondering if you would like to join it..

**Comment by Explosion-Scratch** [comment]
Oh hi! Sure! I think I saw that, hold on...

**Comment by ghost** [comment]
The computernerds forum?
https://computernerds.flarum.cloud/

**Comment by Explosion-Scratch** [comment]
Whoa, that was fast. Yeah.

**Comment by Explosion-Scratch** [comment]
I'm signing up rn

**Comment by Explosion-Scratch** [comment]
Okay! I verified my account and stuff!

**Comment by ghost** [comment]
Great, link to your profile page?

**Comment by Explosion-Scratch** [comment]
No lol

**Comment by Explosion-Scratch** [comment]
I just posted a hi thing.

**Comment by ghost** [comment]
Ohh k

**Comment by Explosion-Scratch** [comment]
Here we go: https://computernerds.flarum.cloud/u/--Explosion--

**Comment by ghost** [comment]
Lemme get everything set up for u

**Comment by Explosion-Scratch** [comment]
Also can you stop editing you posts, it's kinda confusing.

**Comment by Explosion-Scratch** [comment]
Thanks!

**Comment by Explosion-Scratch** [comment]
Whoa.

**Comment by ghost** [comment]
yes?

**Comment by ghost** [comment]
I mean.. i changed your profile pic to your current one :P

**Comment by Explosion-Scratch** [comment]
It updated with my pfp and stuff. Also you spelled 'Python' phyton lol

**Comment by ghost** [comment]
i know, i have a problem

**Comment by Explosion-Scratch** [comment]
How do you like my cover?

**Comment by ghost** [comment]
Coooool! Btw would you like your username change to -Explosion-?

**Comment by ghost** [comment]
Cuz there's really no one with that username :P

**Comment by Explosion-Scratch** [comment]
No, people know me by --Explosion--

**Comment by ghost** [comment]
K! So uh, we have a anti-impersonating system, willya like me to turn it on for your account?

**Comment by Explosion-Scratch** [comment]
> K! So uh, we have a anti-impersonating system, willya like me to turn it on for your account?

Uh, sure? What does that do?

**Comment by ghost** [comment]
It has a really complicated system
But basically, you can't make an account with the username -Explosion-, --ExpIosion-- (The L is replaced with capital i), or anything potentially similar to yours

**Comment by Explosion-Scratch** [comment]
I see. Sure!

**Comment by ghost** [comment]
Ok, please allow up to 5 minutes..

**Comment by Explosion-Scratch** [comment]
lol that sounded official, sure.

**Comment by ghost** [comment]
K, try impersonating yourself now 😂

**Comment by Explosion-Scratch** [comment]
Lol, I don't think I'm going to do that, but...

**Comment by Explosion-Scratch** [comment]
Also I'm closing this for now!
