### ISSUE TITLE
[UNRELATED] chat

### ISSUE THREAD

**Issue by retronbv** [Explosion-Scratch/explosion-scratch.github.io#23]
@Explosion-Scratch hi, there isn’t really a way for us to chat while I’m in irl school. So I figured we could chat here. (Please don’t be mad I made this totally unrelated issue on an unrelated repo

**Comment by Explosion-Scratch** [comment]
Lol didn't they unblock discord now

**Comment by retronbv** [comment]
Yes but that was 16 days ago lmao

**Comment by Explosion-Scratch** [comment]
lmao
