### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [Explosion-Scratch/explosion-scratch.github.io#25]
nice! i have a question: do u know aframe vr? its kinda like blender but much simpler and works for all devices (not mobile tho)

**Comment by Explosion-Scratch** [comment]
Not really, I'll look into it when I get the chance? Is it a 3d editor, renderer, viewer or framework?

**Comment by TheRealDigitalMaster** [comment]
Basically all 3. It works with VR glasses as well.

**Comment by Explosion-Scratch** [comment]
Huh, cool
